# dirDatabase = "data"
dirDatabase = "//192.168.0.105/FireSafety 시간관리/data"
databaseUser = f"{dirDatabase}/User.db"
databaseBusiness = f"{dirDatabase}/Business.db"
databaseInfo = f"{dirDatabase}/Info.db"
databaseMain = f"{dirDatabase}/Main"

# dirImg = "design/img"
dirImg = "//192.168.0.105/FireSafety 시간관리/img"
imgUser = f"{dirImg}/user.png"
imgPeople = f"{dirImg}/people.png"
imgSetting = f"{dirImg}/setting.png"
imgLogo = f"{dirImg}/logo.png"
imgLogin = f"{dirImg}/login.png"
imgBackGround = f"{dirImg}/background.png"

# dirIcon = "design/icon"
dirIcon = "//192.168.0.105/FireSafety 시간관리/icon"
iconIcon = f"{dirIcon}/icon.ico"
